### PR TITLE
Enable package toggling

### PR DESCRIPTION
**Pull request by ChexWarrior**
I've written a small patch that will enable and disable the auto-save package when using the default keymap.

### CODE REVIEW

**Comment by ChexWarrior** [comment]
Ah, I didn't think you were going to merge this in so I kept working. Shall I back these change out and commit them in a more orderly fashion and not include the package changes?

**Comment by isthatcentered** [comment]
Hello Andrew, no need, it's perfectly fine.

I'm glad you used it as a base, this made my day.

I could actually transfer ownership to you if you want
ᐧ

**Comment by ChexWarrior** [comment]
If you don't mind that sounds good to me, I'll unpublish my other package and continue this one.

**Comment by isthatcentered** [comment]
Sure.
Apparently, I can't transfer ownership as long as you have the fork. Can
you close it and I'll start the transfer again.
ᐧ

**Comment by ChexWarrior** [comment]
Thanks, my fork has been removed.

**Comment by isthatcentered** [comment]
You should have received a request for the transfer now :)
ᐧ

**Comment by ChexWarrior** [comment]
Thanks!

**Pull request merged**
